version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: schedule-postgres
    environment:
      POSTGRES_DB: schedule_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      SCHEDULE_DB_PASSWORD: ${SCHEDULE_DB_PASSWORD}
      MIGRATION_DB_PASSWORD: ${MIGRATION_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./database/init.sql:/app/database/init.sql
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - schedule-network

  backend:
    build: .
    container_name: schedule-backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MIGRATION_DATABASE_URL: ${MIGRATION_DATABASE_URL}
      POSTGRES_PASSWORD: postgres_password
      SCHEDULE_DB_PASSWORD: ${SCHEDULE_DB_PASSWORD}
      MIGRATION_DB_PASSWORD: ${MIGRATION_DB_PASSWORD}
      PYTHONPATH: /app
      CORS_ORIGINS: ${CORS_ORIGINS}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - schedule-network
    command: ["/bin/bash", "/app/startup.sh"]

  frontend:
    build:
      context: ${FRONTEND_PATH}
      dockerfile: Dockerfile
    container_name: schedule-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - schedule-network

  frontend-dev:
    build:
      context: ${FRONTEND_PATH}
      dockerfile: Dockerfile.dev  # специальный Dockerfile для разработки
    ports:
      - "5173:5173"               # порт dev-сервера (у Vite по умолчанию 5173)
    volumes:
      - ${FRONTEND_PATH}:/app     # монтируем исходники
      - /app/node_modules          # не даём перезаписать node_modules из образа
    networks:
      - schedule-network
    command: [ "npm", "run", "dev", "--", "--host", "0.0.0.0" ]

volumes:
  postgres_data:

networks:
  schedule-network:
    driver: bridge