"""Initial migration

Revision ID: 29d3ed899ac3
Revises: 
Create Date: 2026-01-21 12:40:46.616783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d3ed899ac3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('event_id'),
    schema='schedule_schema'
    )
    op.create_table('global_group',
    sa.Column('global_group_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('global_group_id'),
    schema='schedule_schema'
    )
    op.create_table('group',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('group_id'),
    schema='schedule_schema'
    )
    op.create_table('subject',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('subject_id'),
    schema='schedule_schema'
    )
    op.create_table('teacher',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('teacher_id'),
    schema='schedule_schema'
    )
    op.create_table('time_group',
    sa.Column('time_group_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('time_group_id'),
    schema='schedule_schema'
    )
    op.create_table('user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('date_registration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    schema='schedule_schema'
    )
    op.create_table('global_group_event',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('global_group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['schedule_schema.event.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['global_group_id'], ['schedule_schema.global_group.global_group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'global_group_id'),
    schema='schedule_schema'
    )
    op.create_table('global_group_group',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('global_group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['global_group_id'], ['schedule_schema.global_group.global_group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['schedule_schema.group.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'global_group_id'),
    schema='schedule_schema'
    )
    op.create_table('global_group_subject',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('global_group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['global_group_id'], ['schedule_schema.global_group.global_group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['schedule_schema.subject.subject_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id', 'global_group_id'),
    schema='schedule_schema'
    )
    op.create_table('global_group_teacher',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('global_group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['global_group_id'], ['schedule_schema.global_group.global_group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['schedule_schema.teacher.teacher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'global_group_id'),
    schema='schedule_schema'
    )
    op.create_table('global_group_time_group',
    sa.Column('time_group_id', sa.UUID(), nullable=False),
    sa.Column('global_group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['global_group_id'], ['schedule_schema.global_group.global_group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_group_id'], ['schedule_schema.time_group.time_group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time_group_id', 'global_group_id'),
    schema='schedule_schema'
    )
    op.create_table('global_group_user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('global_group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['global_group_id'], ['schedule_schema.global_group.global_group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['schedule_schema.user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'global_group_id'),
    schema='schedule_schema'
    )
    op.create_table('lesson_time',
    sa.Column('lesson_time_id', sa.UUID(), nullable=False),
    sa.Column('time_group_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['time_group_id'], ['schedule_schema.time_group.time_group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_time_id'),
    schema='schedule_schema'
    )
    op.create_table('plan',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_format', sa.Enum('ONLINE', 'OFFLINE', name='event_format_enum'), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['schedule_schema.event.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['schedule_schema.group.group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['schedule_schema.subject.subject_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id'),
    schema='schedule_schema'
    )
    op.create_table('lesson',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('lesson_time_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_time_id'], ['schedule_schema.lesson_time.lesson_time_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['schedule_schema.plan.plan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id'),
    schema='schedule_schema'
    )
    op.create_table('teacher_lesson',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['schedule_schema.lesson.lesson_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['schedule_schema.teacher.teacher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'lesson_id'),
    schema='schedule_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_lesson', schema='schedule_schema')
    op.drop_table('lesson', schema='schedule_schema')
    op.drop_table('plan', schema='schedule_schema')
    op.drop_table('lesson_time', schema='schedule_schema')
    op.drop_table('global_group_user', schema='schedule_schema')
    op.drop_table('global_group_time_group', schema='schedule_schema')
    op.drop_table('global_group_teacher', schema='schedule_schema')
    op.drop_table('global_group_subject', schema='schedule_schema')
    op.drop_table('global_group_group', schema='schedule_schema')
    op.drop_table('global_group_event', schema='schedule_schema')
    op.drop_table('user', schema='schedule_schema')
    op.drop_table('time_group', schema='schedule_schema')
    op.drop_table('teacher', schema='schedule_schema')
    op.drop_table('subject', schema='schedule_schema')
    op.drop_table('group', schema='schedule_schema')
    op.drop_table('global_group', schema='schedule_schema')
    op.drop_table('event', schema='schedule_schema')
    # ### end Alembic commands ###
