"""add_teacher_plan

Revision ID: 66009084dc60
Revises: ae21c96aa195
Create Date: 2026-02-17 20:09:10.507182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66009084dc60'
down_revision: Union[str, Sequence[str], None] = 'ae21c96aa195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_plan',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['schedule_schema.plan.plan_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['schedule_schema.teacher.teacher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id', 'teacher_id'),
    schema='schedule_schema'
    )
    op.drop_constraint(op.f('global_group_event_global_group_id_fkey'), 'global_group_event', type_='foreignkey')
    op.drop_constraint(op.f('global_group_event_event_id_fkey'), 'global_group_event', type_='foreignkey')
    op.create_foreign_key(None, 'global_group_event', 'event', ['event_id'], ['event_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    op.create_foreign_key(None, 'global_group_event', 'global_group', ['global_group_id'], ['global_group_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    op.drop_constraint(op.f('global_group_group_global_group_id_fkey'), 'global_group_group', type_='foreignkey')
    op.drop_constraint(op.f('global_group_group_group_id_fkey'), 'global_group_group', type_='foreignkey')
    op.create_foreign_key(None, 'global_group_group', 'global_group', ['global_group_id'], ['global_group_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    op.create_foreign_key(None, 'global_group_group', 'group', ['group_id'], ['group_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    op.drop_constraint(op.f('global_group_subject_global_group_id_fkey'), 'global_group_subject', type_='foreignkey')
    op.drop_constraint(op.f('global_group_subject_subject_id_fkey'), 'global_group_subject', type_='foreignkey')
    op.create_foreign_key(None, 'global_group_subject', 'subject', ['subject_id'], ['subject_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    op.create_foreign_key(None, 'global_group_subject', 'global_group', ['global_group_id'], ['global_group_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    op.drop_constraint(op.f('global_group_teacher_global_group_id_fkey'), 'global_group_teacher', type_='foreignkey')
    op.drop_constraint(op.f('global_group_teacher_teacher_id_fkey'), 'global_group_teacher', type_='foreignkey')
    op.create_foreign_key(None, 'global_group_teacher', 'teacher', ['teacher_id'], ['teacher_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    op.create_foreign_key(None, 'global_group_teacher', 'global_group', ['global_group_id'], ['global_group_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    op.drop_constraint(op.f('global_group_time_group_time_group_id_fkey'), 'global_group_time_group', type_='foreignkey')
    op.drop_constraint(op.f('global_group_time_group_global_group_id_fkey'), 'global_group_time_group', type_='foreignkey')
    op.create_foreign_key(None, 'global_group_time_group', 'time_group', ['time_group_id'], ['time_group_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    op.create_foreign_key(None, 'global_group_time_group', 'global_group', ['global_group_id'], ['global_group_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    op.drop_constraint(op.f('global_group_user_global_group_id_fkey'), 'global_group_user', type_='foreignkey')
    op.drop_constraint(op.f('global_group_user_user_id_fkey'), 'global_group_user', type_='foreignkey')
    op.create_foreign_key(None, 'global_group_user', 'global_group', ['global_group_id'], ['global_group_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    op.create_foreign_key(None, 'global_group_user', 'user', ['user_id'], ['user_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    op.drop_constraint(op.f('lesson_plan_id_fkey'), 'lesson', type_='foreignkey')
    op.drop_constraint(op.f('lesson_lesson_time_id_fkey'), 'lesson', type_='foreignkey')
    op.create_foreign_key(None, 'lesson', 'lesson_time', ['lesson_time_id'], ['lesson_time_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    op.create_foreign_key(None, 'lesson', 'plan', ['plan_id'], ['plan_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    op.drop_constraint(op.f('lesson_time_time_group_id_fkey'), 'lesson_time', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_time', 'time_group', ['time_group_id'], ['time_group_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    op.add_column('plan', sa.Column('global_group_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('plan_event_id_fkey'), 'plan', type_='foreignkey')
    op.drop_constraint(op.f('plan_group_id_fkey'), 'plan', type_='foreignkey')
    op.drop_constraint(op.f('plan_subject_id_fkey'), 'plan', type_='foreignkey')
    op.create_foreign_key(None, 'plan', 'event', ['event_id'], ['event_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    op.create_foreign_key(None, 'plan', 'subject', ['subject_id'], ['subject_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    op.create_foreign_key(None, 'plan', 'group', ['group_id'], ['group_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    op.create_foreign_key(None, 'plan', 'global_group', ['global_group_id'], ['global_group_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    op.drop_constraint(op.f('teacher_lesson_lesson_id_fkey'), 'teacher_lesson', type_='foreignkey')
    op.drop_constraint(op.f('teacher_lesson_teacher_id_fkey'), 'teacher_lesson', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_lesson', 'lesson', ['lesson_id'], ['lesson_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    op.create_foreign_key(None, 'teacher_lesson', 'teacher', ['teacher_id'], ['teacher_id'], source_schema='schedule_schema', referent_schema='schedule_schema', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_lesson', schema='schedule_schema', type_='foreignkey')
    op.drop_constraint(None, 'teacher_lesson', schema='schedule_schema', type_='foreignkey')
    op.create_foreign_key(op.f('teacher_lesson_teacher_id_fkey'), 'teacher_lesson', 'teacher', ['teacher_id'], ['teacher_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('teacher_lesson_lesson_id_fkey'), 'teacher_lesson', 'lesson', ['lesson_id'], ['lesson_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'plan', schema='schedule_schema', type_='foreignkey')
    op.drop_constraint(None, 'plan', schema='schedule_schema', type_='foreignkey')
    op.drop_constraint(None, 'plan', schema='schedule_schema', type_='foreignkey')
    op.drop_constraint(None, 'plan', schema='schedule_schema', type_='foreignkey')
    op.create_foreign_key(op.f('plan_subject_id_fkey'), 'plan', 'subject', ['subject_id'], ['subject_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('plan_group_id_fkey'), 'plan', 'group', ['group_id'], ['group_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('plan_event_id_fkey'), 'plan', 'event', ['event_id'], ['event_id'], ondelete='CASCADE')
    op.drop_column('plan', 'global_group_id')
    op.drop_constraint(None, 'lesson_time', schema='schedule_schema', type_='foreignkey')
    op.create_foreign_key(op.f('lesson_time_time_group_id_fkey'), 'lesson_time', 'time_group', ['time_group_id'], ['time_group_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lesson', schema='schedule_schema', type_='foreignkey')
    op.drop_constraint(None, 'lesson', schema='schedule_schema', type_='foreignkey')
    op.create_foreign_key(op.f('lesson_lesson_time_id_fkey'), 'lesson', 'lesson_time', ['lesson_time_id'], ['lesson_time_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('lesson_plan_id_fkey'), 'lesson', 'plan', ['plan_id'], ['plan_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'global_group_user', schema='schedule_schema', type_='foreignkey')
    op.drop_constraint(None, 'global_group_user', schema='schedule_schema', type_='foreignkey')
    op.create_foreign_key(op.f('global_group_user_user_id_fkey'), 'global_group_user', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('global_group_user_global_group_id_fkey'), 'global_group_user', 'global_group', ['global_group_id'], ['global_group_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'global_group_time_group', schema='schedule_schema', type_='foreignkey')
    op.drop_constraint(None, 'global_group_time_group', schema='schedule_schema', type_='foreignkey')
    op.create_foreign_key(op.f('global_group_time_group_global_group_id_fkey'), 'global_group_time_group', 'global_group', ['global_group_id'], ['global_group_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('global_group_time_group_time_group_id_fkey'), 'global_group_time_group', 'time_group', ['time_group_id'], ['time_group_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'global_group_teacher', schema='schedule_schema', type_='foreignkey')
    op.drop_constraint(None, 'global_group_teacher', schema='schedule_schema', type_='foreignkey')
    op.create_foreign_key(op.f('global_group_teacher_teacher_id_fkey'), 'global_group_teacher', 'teacher', ['teacher_id'], ['teacher_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('global_group_teacher_global_group_id_fkey'), 'global_group_teacher', 'global_group', ['global_group_id'], ['global_group_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'global_group_subject', schema='schedule_schema', type_='foreignkey')
    op.drop_constraint(None, 'global_group_subject', schema='schedule_schema', type_='foreignkey')
    op.create_foreign_key(op.f('global_group_subject_subject_id_fkey'), 'global_group_subject', 'subject', ['subject_id'], ['subject_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('global_group_subject_global_group_id_fkey'), 'global_group_subject', 'global_group', ['global_group_id'], ['global_group_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'global_group_group', schema='schedule_schema', type_='foreignkey')
    op.drop_constraint(None, 'global_group_group', schema='schedule_schema', type_='foreignkey')
    op.create_foreign_key(op.f('global_group_group_group_id_fkey'), 'global_group_group', 'group', ['group_id'], ['group_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('global_group_group_global_group_id_fkey'), 'global_group_group', 'global_group', ['global_group_id'], ['global_group_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'global_group_event', schema='schedule_schema', type_='foreignkey')
    op.drop_constraint(None, 'global_group_event', schema='schedule_schema', type_='foreignkey')
    op.create_foreign_key(op.f('global_group_event_event_id_fkey'), 'global_group_event', 'event', ['event_id'], ['event_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('global_group_event_global_group_id_fkey'), 'global_group_event', 'global_group', ['global_group_id'], ['global_group_id'], ondelete='CASCADE')
    op.drop_table('teacher_plan', schema='schedule_schema')
    # ### end Alembic commands ###
